I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 624, in script
    if ignore1 is True:
  File "game/script.rpy", line 624, in <module>
    if ignore1 is True:
NameError: name 'ignore1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 624, in script
    if ignore1 is True:
  File "C:\Users\novem\Downloads\renpy-7.5.0-sdk.7z\renpy-7.5.0-sdk/renpy/ast.py", line 2095, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\novem\Downloads\renpy-7.5.0-sdk.7z\renpy-7.5.0-sdk/renpy/python.py", line 1080, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\novem\Downloads\renpy-7.5.0-sdk.7z\renpy-7.5.0-sdk/renpy/python.py", line 1073, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 624, in <module>
    if ignore1 is True:
NameError: name 'ignore1' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 7.5.0.22062402
Bystander 1.0
Fri Jul 15 15:55:33 2022
